default: &default
  host: 127.0.0.1
  port: <%= ENV.fetch('DATABASE_PORT') { 3306 } %>
  username: root
  password:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: circle_development

test:
  <<: *default
  database: circle_test
